language: groovy

jdk:
- openjdk7

before_install:
- sudo add-apt-repository -y ppa:groovy-dev/grails
- sudo apt-get update
- sudo apt-get install grails-2.2.5

script: "grails test-app unit: --non-interactive"