site_name: CATCH-A
site_description: 
site_author: Justin Miranda
theme: readthedocs
repo_url: https://github.com/annotationsatharvard/catcha
include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2015, <a href="https://twitter.com/justinmiranda">CATCH-A</a>
google_analytics: ['UA-61763038-2', 'CATCH-A']

pages:
- ['index.md', 'Introduction']

# About
#- ['about/license.md', 'About', 'License']
#- ['about/release-notes.md', 'About', 'Release Notes']
#- ['about/contributing.md', 'About', 'Contributing']

# Admin Guide
#- ['admin-guide/index.md', 'Admin Guide',  'Overview']
- ['admin-guide/installation.md', 'Admin Guide',  'Installation']
- ['admin-guide/getting-started.md', 'Admin Guide', 'Getting Started']
- ['admin-guide/configuration.md', 'Admin Guide', 'Configuration']

# User Guide
#- ['user-guide/index.md', 'User Guide', 'Overview']
- ['user-guide/getting-started.md', 'User Guide', 'Getting Started']
- ['user-guide/api.md', 'User Guide', 'API Docs']
- ['user-guide/authentication.md', 'User Guide', 'Authentication']

# Developer Guide
#- ['developer-guide/index.md', 'Developer Guide',  'Overview']
- ['developer-guide/getting-started.md', 'Developer Guide', 'Getting Started']

# Deployment Guide

# Configuration
#- ['configuration.md', 'Configuration', 'Configuration']

# Installation Guide
#- ['installation/ubuntu.md', 'Installation', 'Ubuntu']
#- ['installation/mac.md', 'Installation', 'Mac OS X']
#- ['installation/windows.md', 'Installation', 'Windows']

# HowTo
# Continuous Integration

# Releases:
#- ['release-notes.md', 'Releases', 'Release Notes']
