site_name: OpenBoxes
site_description: 
site_author: Justin Miranda
theme: readthedocs
repo_url: https://github.com/annotationsatharvard/catcha
include_search: true
#use_absolute_urls: true
use_directory_urls: true
copyright: Copyright &copy; 2015, <a href="https://twitter.com/justinmiranda">CATCH-A</a>
google_analytics: ['UA-61763038-2', 'CATCH-A']

pages:
- ['index.md', 'Home']
#- ['user-guide/writing-your-docs.md', 'User Guide', 'Writing your docs']
#- ['user-guide/styling-your-docs.md', 'User Guide', 'Styling your docs']
#- ['user-guide/configuration.md', 'User Guide', 'Configuration']
#- ['about/license.md', 'About', 'License']
#- ['about/release-notes.md', 'About', 'Release Notes']
#- ['about/contributing.md', 'About', 'Contributing']


# About
#- ['index.md', 'About', '']

# Installation
#- ['installation/index.md', 'Installation',  'Overview']
#- ['installation/ubuntu.md', 'Installation', 'Ubuntu']
#- ['installation/mac.md', 'Installation', 'Mac OS X']
#- ['installation/windows.md', 'Installation', 'Windows']

# Configuration
#- ['configuration.md', 'Configuration', 'Configuration']

# Developer Guide
# Continuous Integration
# User Guide
# HowTo
# Cloud

# Releases:
#- ['release-notes.md', 'Releases', 'Release Notes']
